name: Build Linux Nuget
description: This builds the linux compatible nuget
runs:
  using: composite
  steps:
  - name: Download Version
    uses: actions/download-artifact@v3
    with:
      name: config.txt
      path: ./wrappers/csharp
        
  - name: Download Native Libs
    uses: actions/download-artifact@v3
    with:
      name: artifact-staging
      path: ./wrappers/csharp

  - name: Install nuget
    shell: bash
    run: sudo apt-get install nuget

  - name: Generating Linux Nuget
    working-directory: ./wrappers/csharp/nuget
    shell: bash
    run: python3 GenerateNuget.py -p linux

  - name: Place Artifacts
    shell: bash
    run: mv wrappers/csharp/nuget/Linux/package/*.nupkg .

  - uses: actions/upload-artifact@v3
    with:
      name: nugets
      path: ./*.nupkg