version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates, we only want security updates.
    open-pull-requests-limit: 0