version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/devolutions-crypto"
    schedule:
      interval: "daily"
    assignees:
      - "pdugre"
      - "MathieuMorrissette"
    # Disable version updates, we only want security updates.
    open-pull-requests-limit: 0