version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "pdugre"
      - "MathieuMorrissette"

  - package-ecosystem: "npm"
    directory: "/wrappers/wasm/example"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    assignees:
      - "pdugre"
      - "MathieuMorrissette"



