trigger:
- master

pr:
- master

stages:
- stage: Source_Publishing
  dependsOn: [] 
  jobs:
    - template: yaml-templates/source-publish.yml

- stage: code_formatting_check
  dependsOn: [] 
  jobs:
    - template: yaml-templates/rust-code-formatting-check.yml
    - template: yaml-templates/csharp-code-formatting-check.yml
    
- stage: Native_Build
  dependsOn: []
  jobs:
    - template: yaml-templates/native-build-linux.yml
    - template: yaml-templates/native-build-macos.yml
    - template: yaml-templates/native-build-windows.yml

- stage: Nugets
  dependsOn: Native_Build
  jobs:
    - template: yaml-templates/nugets-linux.yml
    - template: yaml-templates/nugets-macos.yml
    - template: yaml-templates/nugets-windows.yml

  
- stage: WebAssembly
  dependsOn: []
  jobs:
  - template: yaml-templates/safari-unit-tests.yml
  - template: yaml-templates/webassembly-build.yml

- stage: PythonBuild
  dependsOn: []
  jobs:
    - template: yaml-templates/python-build-linux.yml
    - template: yaml-templates/python-build-macos.yml
    - template: yaml-templates/python-build-windows.yml

- stage: PythonTests
  dependsOn: PythonBuild
  jobs:
    - template: yaml-templates/python-unit-tests-linux.yml
    - template: yaml-templates/python-unit-tests-macos.yml
    - template: yaml-templates/python-unit-tests-windows.yml

- stage: CSharpUnitTests
  dependsOn: Nugets
  jobs: 
    - template: yaml-templates/csharp-unit-tests-windows.yml
    - template: yaml-templates/csharp-unit-tests-linux.yml
    - template: yaml-templates/csharp-unit-tests-macos.yml
    - template: yaml-templates/csharp-unit-tests-ios.yml
    - template: yaml-templates/csharp-unit-tests-android.yml  

- stage: CSharpIntegrationTests
  dependsOn: Nugets
  jobs:
    - template: yaml-templates/csharp-integration-tests.yml  
