[package]
name = "uniffi-lib"
edition = "2021"
version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
devolutions-crypto = { path = "../../" }
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
