name: Build Kotlin Package
runs:
  using: composite
  steps:
    - name: Run setup
      working-directory: ./wrappers/kotlin
      shell: bash
      run: sh setup.sh

    - name: Build
      working-directory: ./wrappers/kotlin
      shell: bash
      run: sh build.sh

    - name: Kotlin Package
      uses: actions/upload-artifact@v4
      with:
        name: kotlin
        path: ./wrappers/kotlin/lib/build

