name: Check C# Code Format
description: Ensure that the C# code format is compliant
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - uses: actions/setup-python@v5
      with:
        python-version: "3.7"

    - name:  Setting up PATH environment variable
      shell: bash
      run: |
        echo "c:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn" >> $GITHUB_PATH

    - name: Run .NET format
      shell: bash
      working-directory: ./wrappers/csharp/src/
      run: |
        dotnet tool install -g dotnet-format
        dotnet format devolutions-crypto.csproj --verify-no-changes
