name: Check C# Code Format
description: Ensure that the C# code format is compliant
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - uses: actions/setup-python@v5
      with:
        python-version: "3.7"

    - name:  Setting up PATH environment variable
      shell: bash
      run: |
        echo "c:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn" >> $GITHUB_PATH

    - name: Installing rust targets
      shell: pwsh
      run: |
        rustup target add x86_64-pc-windows-msvc
        rustup target add i686-pc-windows-msvc
        rustup target add aarch64-pc-windows-msvc

    - name: Building Windows
      working-directory: ./wrappers/csharp
      shell: pwsh
      run: python GeneratePackage.py -p windows

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Code Analysis
      working-directory: ./wrappers/csharp/tests/unit-tests/manual/dotnet-framework
      shell: pwsh
      run: msbuild dotnet-framework.sln /t:restore,clean,build /p:TreatWarningsAsErrors=True /p:RunCodeAnalysis=true
