name: Check C# Code Format
description: Ensure that the C# code format is compliant
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Run .NET format
      shell: bash
      working-directory: ./wrappers/csharp/src/
      run: |
        dotnet tool install -g dotnet-format
        dotnet format devolutions-crypto.csproj --verify-no-changes
