[package]
name = "uniffi-builder-macro"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.79", features = ["full", "extra-traits"] }
