name: Native Build Windows
description: This builds the windows nugets
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - uses: actions/setup-python@v5
      with:
        python-version: "3.7"

    - name: Download Native Libs
      uses: actions/download-artifact@v4
      with:
        pattern: native-*
        merge-multiple: true
        path: ./wrappers/csharp

    - name: Downloading nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run : curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe

    - name: Read version from config file
      shell: bash
      working-directory: ./wrappers/csharp
      run: |
          VERSION=$(grep 'version' config.txt | cut -d '=' -f2 | tr -d ' "')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

    - name: Generating DOTNET Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: nuget pack ./dotnet-core/Devolutions.Crypto.Core.nuspec -Version $VERSION -OutputDirectory ./dotnet-core/package

    - name: Place Artifacts
      shell: bash
      run: mv wrappers/csharp/nuget/dotnet-core/package/*.nupkg .

    - uses: actions/upload-artifact@v4.3.6
      with:
        name: nugets-windows
        path: ./*.nupkg
