name: Native Build Windows
description: This builds the windows nugets
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Download Native Libs
      uses: actions/download-artifact@v3
      with:
        name: artifact-staging
        path: ./wrappers/csharp

    - name: Downloading nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run : curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe
    
    - name: Generating WIN Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python GenerateNuget.py -p windows

    - name: Generating DOTNET Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python GenerateNuget.py -p core

    - name: Place Artifacts
      shell: bash
      run: |
        mv wrappers/csharp/nuget/Windows/package/*.nupkg .
        mv wrappers/csharp/nuget/dotnet-core/package/*.nupkg .
        
    - uses: actions/upload-artifact@v3
      with:
        name: nugets
        path: ./*.nupkg
