# Defines a default set of lint rules enforced for projects at Devolutions.
# This line makes the lints from package:lints available.
include: package:lints/recommended.yaml

# Uncomment to enable stricter linting
# include: package:lints/core.yaml

linter:
  rules:
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures

analyzer:
  exclude:
    - lib/src/generated/**
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
