name: Native Build macOS
description: This builds the macOS native libraries
runs:
  using: composite
  steps:
    - name:  Install Rust
      shell: bash
      run: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        source $HOME/.cargo/env

        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

        rustup target add aarch64-apple-ios
        rustup target add x86_64-apple-ios

    - name: Unit tests
      working-directory: ./devolutions-crypto
      shell: bash
      run: |
        source $HOME/.cargo/env
        cargo test
      
    - name: Building Mac Full
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
          source $HOME/.cargo/env
          python3 GeneratePackage.py -p mac
      
    - name: Building Mac Modern
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        source $HOME/.cargo/env
        python3 GeneratePackage.py -p mac-modern

    - name: Building IOS
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        source $HOME/.cargo/env
        python3 GeneratePackage.py -p ios

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-staging
        path: |
          wrappers/csharp/macos-full/**
          wrappers/csharp/macos-modern/**
          wrappers/csharp/ios/**