name: Native Build macOS
description: This builds the macOS native libraries
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v3
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name:  Install Rust
      shell: bash
      run: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
        source $HOME/.cargo/env
        
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Unit tests
      working-directory: ./devolutions-crypto
      shell: bash
      run: |
        source $HOME/.cargo/env
        cargo test
      
    - name: Building Mac Full
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
          source $HOME/.cargo/env
          python3 GeneratePackage.py -p mac
      
    - name: Building Mac Modern
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        source $HOME/.cargo/env
        python3 GeneratePackage.py -p mac-modern

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-staging
        path: |
          wrappers/csharp/macos-full/**
          wrappers/csharp/macos-modern/**