name: Native Build macOS
description: This builds the macOS native libraries
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Install Homebrew
      shell: bash
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "PATH=/opt/homebrew/bin:$PATH" >> $GITHUB_ENV
    
    - name: Verify Homebrew installation
      shell: bash
      run: brew --version
      
    - name: Install mono
      shell: bash
      run: brew install mono

    - name:  Install Rust
      shell: bash
      run: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
        source $HOME/.cargo/env

        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin

    - name: Unit tests
      working-directory: ./
      shell: bash
      run: |
        source $HOME/.cargo/env
        cargo test

    - name: Building Mac Modern
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        source $HOME/.cargo/env
        python3 GeneratePackage.py -p mac-modern

    - name: Prepare folder structure
      working-directory: ./
      shell: bash
      run: |
        mv wrappers/csharp/macos-modern wrappers/csharp/macos-modern-temp
        mkdir -p wrappers/csharp/macos-modern/macos-modern
        mv wrappers/csharp/macos-modern-temp/* wrappers/csharp/macos-modern/macos-modern/
        rmdir wrappers/csharp/macos-modern-temp

    - uses: actions/upload-artifact@v4.3.6
      with:
        name: native-macos
        path: wrappers/csharp/macos-modern/
