/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

 plugins {
    id("com.android.library") version "8.8.0"
    kotlin("android") version "2.1.10"

    id("maven-publish")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "17"
    }
}


dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.jna)
}

android {
    namespace = "org.devolutions.crypto"
    compileSdk = 34

    defaultConfig {
        minSdk = 21
        targetSdk = 34
    }

    lint {
        abortOnError = false
    }
}

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("mavenAndroid") {
                groupId = "devolutions"
                artifactId = "devolutions-crypto-android"
                version = project.version.toString()

                // Use the Android component explicitly
                from(components["release"])

                pom {
                    name.set("Devolutions Crypto (Android)")
                    description.set("Devolutions Cryptographic Library for Android")
                    url.set("https://github.com/devolutions/devolutions-crypto")

                    licenses {
                        license {
                            name.set("Apache License 2.0")
                            url.set("https://www.apache.org/licenses/LICENSE-2.0.html")
                        }
                    }
                }
            }
        }
    }
}

