jobs:
- job: csharp_unit_tests_macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "Nugets"
      targetPath: "./wrappers/csharp/tests/unit-tests/nugets/Nugets"
  - script: |
      sudo nuget update -self
    displayName: "Update Nuget"

  - script: |
      curl -o xamarinmac.pkg 'https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg'

      sudo installer -pkg xamarinmac.pkg -target /
    displayName: "Workaround for Xamarin.Mac bug"
    # https://github.com/xamarin/xamarin-macios/issues/10652


  - script: |
      python3 unit-tests.py -p core
    workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
    displayName: "Unit tests DOTNET CORE"

  - script: |
      python3 unit-tests.py -p mac
    workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
    displayName: "Unit tests XAMARIN-MAC-FULL"

  - script: |
      python3 unit-tests.py -p mac-modern
    workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
    displayName: "Unit tests XAMARIN-MAC-MODERN"
