jobs: 
- job: csharp_unit_tests_windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - checkout: self
      lfs: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
        
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "Nugets"
        targetPath: "./wrappers/csharp/tests/unit-tests/nugets/Nugets"

    - bash: |
        echo "##vso[task.prependpath]c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
        echo "##vso[task.prependpath]c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
      displayName: "setting up PATH environment variable"

    - script: | 
        curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe --output nuget.exe
      workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
      displayName: "Downloading nuget"

    - script: |
        python unit-tests.py -p framework
      workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
      displayName: "Unit tests DOTNET FRAMEWORK PACKAGE CONFIG"
    
    - script: |
        python unit-tests.py -p core
      workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
      displayName: "Unit tests DOTNET CORE"