jobs:
- job: csharp_unit_tests_linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self
      lfs: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "Nugets"
        targetPath: "./wrappers/csharp/tests/unit-tests/nugets/Nugets"

    - script: |
        sudo apt install nuget
      displayName: "Install nuget"

    - script: |
        python unit-tests.py -p core
      workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
      displayName: "Unit tests DOTNET CORE"
