jobs:
- job: csharp_code_formatting_check
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    lfs: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - bash: |
      echo "##vso[task.prependpath]c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn"        
      echo "##vso[task.prependpath]c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
    displayName: "Setting up PATH environment variable"

  - script: |
      #rustup update
      rustup target add x86_64-pc-windows-msvc
      rustup target add i686-pc-windows-msvc
    displayName: "Installing rust targets"

  - script: |
      python GeneratePackage.py -p windows
    workingDirectory: "./wrappers/csharp"
    displayName: "Building Windows"

  - script: | 
      msbuild dotnet-framework.sln /t:restore,clean,build /p:TreatWarningsAsErrors=True;RunCodeAnalysis=true
    workingDirectory: "./wrappers/csharp/tests/unit-tests/manual/dotnet-framework"
    displayName: "Code Analysis"