jobs:
- job: csharp_unit_tests_ios
  pool:
    vmImage: 'macOS-latest'
  steps:
  - checkout: self
    lfs: true
    submodules: true
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "Nugets"
      targetPath: "./wrappers/csharp/tests/unit-tests/nugets/Nugets"
  - script: |
      sudo nuget update -self
    displayName: "Update Nuget"

  - script: |
      python3 unit-tests.py -p ios
    workingDirectory: "./wrappers/csharp/tests/unit-tests/nugets"
    displayName: "Unit tests XAMARIN-IOS"