jobs:
- job: native_build_linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      sudo apt update
      sudo apt install nuget gcc-multilib software-properties-common
    displayName: "Installing dependencies"

  - script: |
      rustup update

      rustup target add x86_64-unknown-linux-gnu
      rustup target add i686-unknown-linux-gnu

      rustup target add aarch64-linux-android
      rustup target add armv7-linux-androideabi
      rustup target add i686-linux-android
      rustup target add x86_64-linux-android

      mkdir .cargo
    displayName: "Install rust"
          
  - script: |
      cargo test
    workingDirectory: "./devolutions-crypto"
    displayName: "Unit tests"  

  - script: |
      python GeneratePackage.py -p linux
    workingDirectory: "./wrappers/csharp"
    displayName: "Building Linux"

  - script: |
      export ANDROID_HOME=/usr/local/lib/android/sdk        
      export NDK_HOME=$ANDROID_HOME/ndk-bundle

      echo "[target.aarch64-linux-android]
      ar = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar\"
      linker = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang\"
      [target.armv7-linux-androideabi]
      ar = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar\"
      linker = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang\"
      [target.i686-linux-android]
      ar = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar\"
      linker = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android16-clang\"
      [target.x86_64-linux-android]
      ar = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar\"
      linker = \"$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang\"" >> ./.cargo/config

  - script: |
      export ANDROID_HOME=/usr/local/lib/android/sdk        
      export NDK_HOME=$ANDROID_HOME/ndk-bundle

      python GeneratePackage.py -p android
    workingDirectory: "./wrappers/csharp"
    displayName: "Building Android"

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/android/**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/linux/**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: MyBuildOutputs
