jobs:
- job: nugets_linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "MyBuildOutputs"
      targetPath: "."
  
  - script: |
      sudo apt install nuget
    displayName: "Install nuget"

  - script: |
      python3 GenerateNuget.py -p linux
    workingDirectory: "./wrappers/csharp/nuget"
    displayName: "Generating Linux Nuget"

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/nuget/Linux/package/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)/general

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/general
      artifactName: Nugets