jobs:
- job: nugets_macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "MyBuildOutputs"
      targetPath: "."
  - script: |
      sudo nuget update -self
    displayName: "Update Nuget"

  - script: |
      python3 GenerateNuget.py -p ios
    workingDirectory: "./wrappers/csharp/nuget"
    displayName: "Generating IOS Nuget"

  - script: |
      python3 GenerateNuget.py -p mac-modern
    workingDirectory: "./wrappers/csharp/nuget"
    displayName: "Generating MAC-MODERN Nuget"

  - script: |
      python3 GenerateNuget.py -p mac
    workingDirectory: "./wrappers/csharp/nuget"
    displayName: "Generating MAC-FULL Nuget"

  - script: |
      python3 GenerateNuget.py -p android
    workingDirectory: "./wrappers/csharp/nuget"
    displayName: "Generating Android Nuget"
  

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/nuget/iOS/Devolutions.Crypto.iOS/package/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)/general

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/nuget/macOS/Full/package/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)/general

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/nuget/macOS/Modern/Devolutions.Crypto.Mac/package/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)/general

  - task: CopyFiles@2
    inputs:
      contents: 'wrappers/csharp/nuget/Android/Devolutions.Crypto.Android/package/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)/general

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/general
      artifactName: Nugets