jobs:
- job: python_build_linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - script: |
      sudo apt update
      sudo apt install nuget gcc-multilib software-properties-common
    displayName: "Installing dependencies"

  - script: |
      rustup update
      rustup target add x86_64-unknown-linux-gnu
      mkdir .cargo
    displayName: "Install rust"
          
  - script: |
      pip install maturin
    workingDirectory: "./devolutions-crypto"
    displayName: "Install Maturin"

  - script: |
      maturin sdist
    workingDirectory: "./devolutions-crypto"
    displayName: "Building sdist"
  
  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-unknown-linux-gnu"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.8 Wheel"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
    
  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-unknown-linux-gnu"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.7 Wheel"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
    
  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-unknown-linux-gnu"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.6 Wheel"

  - task: CopyFiles@2
    inputs:
      contents: 'devolutions-crypto/target/wheels/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
      artifactName: PythonWheels