jobs:
- job: python_unit_tests_macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "PythonWheels"
      targetPath: "./wheels"
          
  - script: |
      python -m venv venv python
      source venv/bin/activate
    workingDirectory: "./wrappers/python"
    displayName: "Create virtual environment"

  - script: |
      pip install --find-links="./" devolutions_crypto
    workingDirectory: "./wheels"
    displayName: "Install wheel"

  - script: |
      python -m unittest tests/*.py
    workingDirectory: "./wrappers/python"
    displayName: "Run tests"