jobs:
- job: python_build_macos
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      architecture: 'x64'
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      source $HOME/.cargo/env

      rustup target add x86_64-apple-darwin
    displayName: "Install rust"

  - script: |
      pip install maturin
    workingDirectory: "./devolutions-crypto"
    displayName: "Install maturin"

  - script: |
      source $HOME/.cargo/env
      
      maturin build --no-sdist --release -i python --cargo-extra-args="--features python --target=x86_64-apple-darwin"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.9 Wheel"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'
  
  - script: |
      source $HOME/.cargo/env
      
      maturin build --no-sdist --release -i python --cargo-extra-args="--features python --target=x86_64-apple-darwin"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.8 Wheel"
  
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  
  - script: |
      source $HOME/.cargo/env
      
      maturin build --no-sdist --release -i python --cargo-extra-args="--features python --target=x86_64-apple-darwin"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.7 Wheel"
  
  - task: CopyFiles@2
    inputs:
      contents: 'devolutions-crypto/target/wheels/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      flattenFolders: true
      artifactName: PythonWheels