jobs:
- job: python_build_windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: self
    lfs: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - bash: |
      echo "##vso[task.prependpath]c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn"
    displayName: "Setting up PATH environment variable"

  - script: |
      rustup target add x86_64-pc-windows-msvc
    displayName: "Installing rust targets"

  - script: |
      pip install maturin
    workingDirectory: "./devolutions-crypto"
    displayName: "Install maturin"

  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-pc-windows-msvc"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.8"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'

  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-pc-windows-msvc"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.7"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - script: |
      maturin build --no-sdist -i python --release --cargo-extra-args="--features python --target=x86_64-pc-windows-msvc"
    workingDirectory: "./devolutions-crypto"
    displayName: "Building x86_64 3.6"
  
  - task: CopyFiles@2
    inputs:
      contents: 'devolutions-crypto/target/wheels/**'
      flattenFolders: true
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: PythonWheels