jobs:
- job: python_unit_tests_windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      architecture: 'x64'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: "PythonWheels"
      targetPath: "./wheels"
          
  - script: |
      python -m venv venv python
      venv\Scripts\activate.bat
    workingDirectory: "./wrappers/python"
    displayName: "Create virtual environment"

  - script: |
      pip install --find-links="./" devolutions_crypto
    workingDirectory: "./wheels"
    displayName: "Install wheel"

  - script: |
      python -m unittest discover -p "*"
    workingDirectory: "./wrappers/python/tests/"
    displayName: "Run tests"