jobs:
- job: rust_code_formatting_check
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: |
      rustup update

      mkdir .cargo
    displayName: "Install rust"

  - script: |
      cargo fmt --all -- --check
    workingDirectory: "./devolutions-crypto"
    displayName: "Check Format"

  - script: |
      cargo clippy -- --D warnings
    workingDirectory: "./devolutions-crypto"
    displayName: "Check Clippy"