name: Native Build iOS
description: This builds the iOS native libraries
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Install Homebrew
      shell: bash
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "PATH=/opt/homebrew/bin:$PATH" >> $GITHUB_ENV
    
    - name: Verify Homebrew installation
      shell: bash
      run: brew --version
      
    - name: Install mono
      shell: bash
      run: brew install mono

    - name:  Install Rust
      shell: bash
      run: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Setup iOS minimum version
      shell: bash
      run: echo "IPHONEOS_DEPLOYMENT_TARGET=12.1" >> $GITHUB_ENV

    - name: Install rust
      shell: bash
      run: |
        rustup update

        rustup target add x86_64-apple-ios # iOS Simulator on Intel based mac
        rustup target add aarch64-apple-ios-sim # iOS Simulator on Arm based mac
        rustup target add aarch64-apple-ios # iOS & iPad

    - name: Unit tests
      working-directory: ./
      shell: bash
      run: |
        source $HOME/.cargo/env
        cargo test

    - name: Build iOS
      shell: bash
      run: |
        cargo build --release --target=x86_64-apple-ios
        cargo build --release --target=aarch64-apple-ios-sim
        cargo build --release --target=aarch64-apple-ios

    - name: Making the universal binary
      shell: bash
      run: |
        lipo "../../target/x86_64-apple-ios/release/libDevolutionsCrypto.dylib" \
            "../../target/aarch64-apple-ios/release/libDevolutionsCrypto.dylib" \
            "../../target/aarch64-apple-ios-sim/release/libDevolutionsCrypto.dylib" \
            -create -output "./ios/bin/universal/libDevolutionsCrypto.dylib"

    - name: Create .framework
      shell: bash
      run: |
        mkdir ./ios/bin/universal/libDevolutionsCrypto.framework
        mv ./ios/bin/universal/libDevolutionsCrypto.dylib ./ios/bin/universal/libDevolutionsCrypto.framework/libDevolutionsCrypto

        # Fixing rpath
        echo "Fixing rpath"
        install_name_tool -id "@rpath/libDevolutionsCrypto.framework/libDevolutionsCrypto" "./ios/bin/universal/libDevolutionsCrypto.framework/libDevolutionsCrypto"

        mkdir output
        mv ./ios ./output/ios

    - uses: actions/upload-artifact@v4.3.6
      with:
        name: native-ios
        path: wrappers/csharp/output/**
