name: Native Build iOS
description: This builds the iOS native libraries
runs:
  using: composite
  steps:
    - name: Download Version
      uses: actions/download-artifact@v3
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name:  Install Rust
      shell: bash
      run: |
        set -e
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Setup iOS minimum version
      shell: bash
      run: echo "IPHONEOS_DEPLOYMENT_TARGET=12.1" >> $GITHUB_ENV

    - name: Install rust 
      shell: bash
      run: |
        rustup update

        rustup target add x86_64-apple-ios
        rustup target add aarch64-apple-ios

    - name: Unit tests
      working-directory: ./devolutions-crypto
      shell: bash
      run: |
        source $HOME/.cargo/env
        cargo test

    - name: Building IOS
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        source $HOME/.cargo/env
        python3 GeneratePackage.py -p ios
        mkdir output
        mv ./ios ./output/ios
        

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-staging
        path: wrappers/csharp/output/**