// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(devolutions_crypto_uniffiFFI)
import devolutions_crypto_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_devolutions_crypto_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_devolutions_crypto_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDevolutionsCryptoUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol Argon2ParametersProtocol: AnyObject, Sendable {
    
    func getBytes()  -> Data
    
}
open class Argon2Parameters: Argon2ParametersProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_devolutions_crypto_uniffi_fn_clone_argon2parameters(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_devolutions_crypto_uniffi_fn_free_argon2parameters(handle, $0) }
    }

    
public static func newFromBytes(data: Data)throws  -> Argon2Parameters  {
    return try  FfiConverterTypeArgon2Parameters_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_constructor_argon2parameters_new_from_bytes(
        FfiConverterData.lower(data),$0
    )
})
}
    

    
open func getBytes() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parameters_get_bytes(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArgon2Parameters: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Argon2Parameters

    public static func lift(_ handle: UInt64) throws -> Argon2Parameters {
        return Argon2Parameters(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Argon2Parameters) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Argon2Parameters {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Argon2Parameters, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Parameters_lift(_ handle: UInt64) throws -> Argon2Parameters {
    return try FfiConverterTypeArgon2Parameters.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Parameters_lower(_ value: Argon2Parameters) -> UInt64 {
    return FfiConverterTypeArgon2Parameters.lower(value)
}






public protocol Argon2ParametersBuilderProtocol: AnyObject, Sendable {
    
    func associatedData(value: Data)  -> Argon2ParametersBuilder
    
    func build()  -> Argon2Parameters
    
    func dcVersion(value: UInt32)  -> Argon2ParametersBuilder
    
    func iterations(value: UInt32)  -> Argon2ParametersBuilder
    
    func lanes(value: UInt32)  -> Argon2ParametersBuilder
    
    func length(value: UInt32)  -> Argon2ParametersBuilder
    
    func memory(value: UInt32)  -> Argon2ParametersBuilder
    
    func salt(value: Data)  -> Argon2ParametersBuilder
    
    func secretKey(value: Data)  -> Argon2ParametersBuilder
    
    func variant(value: Argon2Variant)  -> Argon2ParametersBuilder
    
    func version(value: Argon2Version)  -> Argon2ParametersBuilder
    
}
open class Argon2ParametersBuilder: Argon2ParametersBuilderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_devolutions_crypto_uniffi_fn_clone_argon2parametersbuilder(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_constructor_argon2parametersbuilder_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_devolutions_crypto_uniffi_fn_free_argon2parametersbuilder(handle, $0) }
    }

    

    
open func associatedData(value: Data) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_associated_data(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(value),$0
    )
})
}
    
open func build() -> Argon2Parameters  {
    return try!  FfiConverterTypeArgon2Parameters_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_build(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func dcVersion(value: UInt32) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_dc_version(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func iterations(value: UInt32) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_iterations(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func lanes(value: UInt32) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_lanes(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func length(value: UInt32) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_length(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func memory(value: UInt32) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_memory(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(value),$0
    )
})
}
    
open func salt(value: Data) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_salt(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(value),$0
    )
})
}
    
open func secretKey(value: Data) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_secret_key(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(value),$0
    )
})
}
    
open func variant(value: Argon2Variant) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_variant(
            self.uniffiCloneHandle(),
        FfiConverterTypeArgon2Variant_lower(value),$0
    )
})
}
    
open func version(value: Argon2Version) -> Argon2ParametersBuilder  {
    return try!  FfiConverterTypeArgon2ParametersBuilder_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_argon2parametersbuilder_version(
            self.uniffiCloneHandle(),
        FfiConverterTypeArgon2Version_lower(value),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArgon2ParametersBuilder: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Argon2ParametersBuilder

    public static func lift(_ handle: UInt64) throws -> Argon2ParametersBuilder {
        return Argon2ParametersBuilder(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Argon2ParametersBuilder) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Argon2ParametersBuilder {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Argon2ParametersBuilder, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2ParametersBuilder_lift(_ handle: UInt64) throws -> Argon2ParametersBuilder {
    return try FfiConverterTypeArgon2ParametersBuilder.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2ParametersBuilder_lower(_ value: Argon2ParametersBuilder) -> UInt64 {
    return FfiConverterTypeArgon2ParametersBuilder.lower(value)
}






public protocol SigningKeyPairProtocol: AnyObject, Sendable {
    
    func getPrivateKey()  -> Data
    
    func getPublicKey()  -> Data
    
}
open class SigningKeyPair: SigningKeyPairProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_devolutions_crypto_uniffi_fn_clone_signingkeypair(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_devolutions_crypto_uniffi_fn_free_signingkeypair(handle, $0) }
    }

    
public static func newFromBytes(data: Data)throws  -> SigningKeyPair  {
    return try  FfiConverterTypeSigningKeyPair_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_constructor_signingkeypair_new_from_bytes(
        FfiConverterData.lower(data),$0
    )
})
}
    

    
open func getPrivateKey() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_signingkeypair_get_private_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getPublicKey() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_method_signingkeypair_get_public_key(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSigningKeyPair: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SigningKeyPair

    public static func lift(_ handle: UInt64) throws -> SigningKeyPair {
        return SigningKeyPair(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SigningKeyPair) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SigningKeyPair {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SigningKeyPair, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSigningKeyPair_lift(_ handle: UInt64) throws -> SigningKeyPair {
    return try FfiConverterTypeSigningKeyPair.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSigningKeyPair_lower(_ value: SigningKeyPair) -> UInt64 {
    return FfiConverterTypeSigningKeyPair.lower(value)
}




public struct KeyPair: Equatable, Hashable {
    public var privateKey: Data
    public var publicKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(privateKey: Data, publicKey: Data) {
        self.privateKey = privateKey
        self.publicKey = publicKey
    }

    
}

#if compiler(>=6)
extension KeyPair: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KeyPair {
        return
            try KeyPair(
                privateKey: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: KeyPair, into buf: inout [UInt8]) {
        FfiConverterData.write(value.privateKey, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPair_lift(_ buf: RustBuffer) throws -> KeyPair {
    return try FfiConverterTypeKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKeyPair_lower(_ value: KeyPair) -> RustBuffer {
    return FfiConverterTypeKeyPair.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Argon2Variant: Equatable, Hashable {
    
    case argon2d
    case argon2i
    case argon2id



}

#if compiler(>=6)
extension Argon2Variant: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArgon2Variant: FfiConverterRustBuffer {
    typealias SwiftType = Argon2Variant

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Argon2Variant {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .argon2d
        
        case 2: return .argon2i
        
        case 3: return .argon2id
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Argon2Variant, into buf: inout [UInt8]) {
        switch value {
        
        
        case .argon2d:
            writeInt(&buf, Int32(1))
        
        
        case .argon2i:
            writeInt(&buf, Int32(2))
        
        
        case .argon2id:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Variant_lift(_ buf: RustBuffer) throws -> Argon2Variant {
    return try FfiConverterTypeArgon2Variant.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Variant_lower(_ value: Argon2Variant) -> RustBuffer {
    return FfiConverterTypeArgon2Variant.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Argon2Version: Equatable, Hashable {
    
    case version10
    case version13



}

#if compiler(>=6)
extension Argon2Version: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArgon2Version: FfiConverterRustBuffer {
    typealias SwiftType = Argon2Version

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Argon2Version {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .version10
        
        case 2: return .version13
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Argon2Version, into buf: inout [UInt8]) {
        switch value {
        
        
        case .version10:
            writeInt(&buf, Int32(1))
        
        
        case .version13:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Version_lift(_ buf: RustBuffer) throws -> Argon2Version {
    return try FfiConverterTypeArgon2Version.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArgon2Version_lower(_ value: Argon2Version) -> RustBuffer {
    return FfiConverterTypeArgon2Version.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCiphertextVersion: FfiConverterRustBuffer {
    typealias SwiftType = CiphertextVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCiphertextVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCiphertextVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeKeyVersion: FfiConverterRustBuffer {
    typealias SwiftType = KeyVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeKeyVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeKeyVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePasswordHashVersion: FfiConverterRustBuffer {
    typealias SwiftType = PasswordHashVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePasswordHashVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePasswordHashVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSecretSharingVersion: FfiConverterRustBuffer {
    typealias SwiftType = SecretSharingVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSecretSharingVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSecretSharingVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSignatureVersion: FfiConverterRustBuffer {
    typealias SwiftType = SignatureVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSignatureVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSignatureVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSigningKeyVersion: FfiConverterRustBuffer {
    typealias SwiftType = SigningKeyVersion?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSigningKeyVersion.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSigningKeyVersion.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}
public func base64Decode(data: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_base64_decode(
        FfiConverterString.lower(data),$0
    )
})
}
public func base64DecodeUrl(data: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_base64_decode_url(
        FfiConverterString.lower(data),$0
    )
})
}
public func base64Encode(data: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_base64_encode(
        FfiConverterData.lower(data),$0
    )
})
}
public func base64EncodeUrl(data: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_base64_encode_url(
        FfiConverterData.lower(data),$0
    )
})
}
public func decrypt(data: Data, key: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_decrypt(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),$0
    )
})
}
public func decryptAsymmetric(data: Data, key: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_decrypt_asymmetric(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),$0
    )
})
}
public func decryptAsymmetricWithAad(data: Data, key: Data, aad: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_decrypt_asymmetric_with_aad(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterData.lower(aad),$0
    )
})
}
public func decryptWithAad(data: Data, key: Data, aad: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_decrypt_with_aad(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterData.lower(aad),$0
    )
})
}
public func deriveKeyArgon2(key: Data, parameters: Argon2Parameters)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_derive_key_argon2(
        FfiConverterData.lower(key),
        FfiConverterTypeArgon2Parameters_lower(parameters),$0
    )
})
}
public func deriveKeyPbkdf2(key: Data, salt: Data?, iterations: UInt32 = UInt32(10000), length: UInt32 = UInt32(32)) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_derive_key_pbkdf2(
        FfiConverterData.lower(key),
        FfiConverterOptionData.lower(salt),
        FfiConverterUInt32.lower(iterations),
        FfiConverterUInt32.lower(length),$0
    )
})
}
public func encrypt(data: Data, key: Data, version: CiphertextVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_encrypt(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterOptionTypeCiphertextVersion.lower(version),$0
    )
})
}
public func encryptAsymmetric(data: Data, key: Data, version: CiphertextVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_encrypt_asymmetric(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterOptionTypeCiphertextVersion.lower(version),$0
    )
})
}
public func encryptAsymmetricWithAad(data: Data, key: Data, aad: Data, version: CiphertextVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_encrypt_asymmetric_with_aad(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterData.lower(aad),
        FfiConverterOptionTypeCiphertextVersion.lower(version),$0
    )
})
}
public func encryptWithAad(data: Data, key: Data, aad: Data, version: CiphertextVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_encrypt_with_aad(
        FfiConverterData.lower(data),
        FfiConverterData.lower(key),
        FfiConverterData.lower(aad),
        FfiConverterOptionTypeCiphertextVersion.lower(version),$0
    )
})
}
public func generateKey(length: UInt32 = UInt32(32))throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_generate_key(
        FfiConverterUInt32.lower(length),$0
    )
})
}
public func generateKeypair(version: KeyVersion? = nil) -> KeyPair  {
    return try!  FfiConverterTypeKeyPair_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_generate_keypair(
        FfiConverterOptionTypeKeyVersion.lower(version),$0
    )
})
}
public func generateSharedKey(nShares: UInt8, threshold: UInt8, length: UInt32 = UInt32(32), version: SecretSharingVersion? = nil)throws  -> [Data]  {
    return try  FfiConverterSequenceData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_generate_shared_key(
        FfiConverterUInt8.lower(nShares),
        FfiConverterUInt8.lower(threshold),
        FfiConverterUInt32.lower(length),
        FfiConverterOptionTypeSecretSharingVersion.lower(version),$0
    )
})
}
public func generateSigningKeypair(version: SigningKeyVersion? = nil) -> SigningKeyPair  {
    return try!  FfiConverterTypeSigningKeyPair_lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_generate_signing_keypair(
        FfiConverterOptionTypeSigningKeyVersion.lower(version),$0
    )
})
}
public func hashPassword(password: Data, iterations: UInt32 = UInt32(10000), version: PasswordHashVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_hash_password(
        FfiConverterData.lower(password),
        FfiConverterUInt32.lower(iterations),
        FfiConverterOptionTypePasswordHashVersion.lower(version),$0
    )
})
}
public func joinShares(shares: [Data])throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_join_shares(
        FfiConverterSequenceData.lower(shares),$0
    )
})
}
public func mixKeyExchange(privateKey: Data, publicKey: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_mix_key_exchange(
        FfiConverterData.lower(privateKey),
        FfiConverterData.lower(publicKey),$0
    )
})
}
public func sign(data: Data, keypair: Data, version: SignatureVersion? = nil)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_sign(
        FfiConverterData.lower(data),
        FfiConverterData.lower(keypair),
        FfiConverterOptionTypeSignatureVersion.lower(version),$0
    )
})
}
public func validateHeader(data: Data, dataType: DataType) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_devolutions_crypto_uniffi_fn_func_validate_header(
        FfiConverterData.lower(data),
        FfiConverterTypeDataType_lower(dataType),$0
    )
})
}
public func verifyPassword(password: Data, hash: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_verify_password(
        FfiConverterData.lower(password),
        FfiConverterData.lower(hash),$0
    )
})
}
public func verifySignature(data: Data, publicKey: Data, signature: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_devolutions_crypto_uniffi_fn_func_verify_signature(
        FfiConverterData.lower(data),
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(signature),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_devolutions_crypto_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_base64_decode() != 15059) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_base64_decode_url() != 15429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_base64_encode() != 61134) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_base64_encode_url() != 31513) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_decrypt() != 39921) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_decrypt_asymmetric() != 6283) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_decrypt_asymmetric_with_aad() != 45166) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_decrypt_with_aad() != 43775) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_derive_key_argon2() != 27403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_derive_key_pbkdf2() != 32212) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_encrypt() != 28651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_encrypt_asymmetric() != 17008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_encrypt_asymmetric_with_aad() != 61461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_encrypt_with_aad() != 29699) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_generate_key() != 29427) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_generate_keypair() != 38891) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_generate_shared_key() != 57051) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_generate_signing_keypair() != 51146) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_hash_password() != 12769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_join_shares() != 65529) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_mix_key_exchange() != 21197) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_sign() != 42756) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_validate_header() != 53669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_verify_password() != 7704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_func_verify_signature() != 51084) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parameters_get_bytes() != 26758) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_associated_data() != 27028) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_build() != 8751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_dc_version() != 35235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_iterations() != 15990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_lanes() != 57040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_length() != 65258) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_memory() != 41617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_salt() != 5080) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_secret_key() != 14932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_variant() != 48907) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_argon2parametersbuilder_version() != 31568) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_signingkeypair_get_private_key() != 2977) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_method_signingkeypair_get_public_key() != 50462) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_constructor_argon2parameters_new_from_bytes() != 58986) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_constructor_argon2parametersbuilder_new() != 40769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_devolutions_crypto_uniffi_checksum_constructor_signingkeypair_new_from_bytes() != 59560) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiEnsureDevolutionsCryptoInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDevolutionsCryptoUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all