name: Test Swift Package
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Generate package
      working-directory: ./wrappers/swift
      shell: bash
      run: sh generate.sh

    - name: Upload package
      uses: actions/upload-artifact@v4.3.6
      with:
        name: swift
        path: ./wrappers/swift/package
