name: Publish Source
description: This package the source code used for this build.
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v4.3.6
    with:
      name: source
      path: |
        **/*
        !.git/**/*
