/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import uniffi.uniffi_lib.hello

class Library {
    fun someLibraryMethod(): Boolean {
        hello();

        return true
    }
}
