name: Build macOS Nuget
description: This builds the macos compatible nuget
runs:
  using: composite
  steps:
    - name: Download Version
      uses: actions/download-artifact@v3
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Download Native Libs
      uses: actions/download-artifact@v3
      with:
        name: artifact-staging
        path: ./wrappers/csharp

    - name: Update Nuget
      shell: bash
      run: sudo nuget update -self

    # dotnet restore fails on macos-11
    # https://github.com/actions/virtual-environments/issues/5768
    - name: Nuget workaround
      shell: bash
      run: |
        rm -rf ~/.config/NuGet/NuGet.Config
        dotnet nuget list source

    - name: Generating IOS Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p ios

    - name: Generating MAC-MODERN Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p mac-modern

    - name: Generating MAC-FULL Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p mac

    - name: Generating Android Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p android

    - name: Place Artifacts
      shell: bash
      run: |
        mv wrappers/csharp/nuget/iOS/Devolutions.Crypto.iOS/package/*.nupkg .
        mv wrappers/csharp/nuget/macOS/Full/package/*.nupkg .
        mv wrappers/csharp/nuget/macOS/Modern/Devolutions.Crypto.Mac/package/*.nupkg .
        mv wrappers/csharp/nuget/Android/Devolutions.Crypto.Android/package/*.nupkg .
        
    - uses: actions/upload-artifact@v3
      with:
        name: nugets
        path: ./*.nupkg