name: Build macOS Nuget
description: This builds the macos compatible nuget
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v4
      with:
        name: config.txt
        path: ./wrappers/csharp

    - name: Download Native Libs
      uses: actions/download-artifact@v4
      with:
        pattern: native-*
        merge-multiple: true
        path: ./wrappers/csharp

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install iOS Workload
      shell: bash
      run: sudo dotnet workload install ios

    - name: Install macOS Workload
      shell: bash
      run: sudo dotnet workload install macos

    - name: Install android Workload
      shell: bash
      run: sudo dotnet workload install android

    # dotnet restore fails on macos-12
    # https://github.com/actions/virtual-environments/issues/5768
    - name: Nuget workaround
      shell: bash
      run: |
        rm -rf ~/.config/NuGet/NuGet.Config
        dotnet nuget list source

    - name: Generating IOS Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p ios

    - name: Generating MAC-MODERN Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p mac-modern

    - name: Generating Android Nuget
      working-directory: ./wrappers/csharp/nuget
      shell: bash
      run: python3 GenerateNuget.py -p android

    - name: Place Artifacts
      shell: bash
      run: |
        mv wrappers/csharp/nuget/iOS/Devolutions.Crypto.iOS/package/*.nupkg .
        mv wrappers/csharp/nuget/macOS/Modern/Devolutions.Crypto.Mac/package/*.nupkg .
        mv wrappers/csharp/nuget/Android/Devolutions.Crypto.Android/package/*.nupkg .

    - uses: actions/upload-artifact@v4.3.6
      with:
        name: nugets-macos
        path: ./*.nupkg
