/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    implementation("net.java.dev.jna:jna:5.10.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {

    doFirst {
   // systemProperty("java.library.path", file("native-libs").absolutePath)
   // systemProperty("PATH", file("native-libs").absolutePath)
    //systemProperty("jna.library.path", file("native-libs").absolutePath)
  //  systemProperty("java.class.path", file("native-libs").absolutePath)



    //systemProperty("jna.library.path", file("$projectDir/lib/native-libs").absolutePath)
    //systemProperty("jna.library.path", file("native-libs").absolutePath)

   /* 
    val nativeLibPath = file("native-libs").absolutePath
    systemProperty("java.library.path", nativeLibPath)

        println("Library path: $nativeLibPath")
    }
*/
    }
        // Use JUnit Platform for unit tests.
        useJUnitPlatform()

}


