name: Native Build Windows
description: This builds the windows native libraries
runs:
  using: composite
  steps:
    - name: Download Config
      uses: actions/download-artifact@v3
      with:
        name: config.txt
        path: ./wrappers/csharp

    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name:  Setting up PATH environment variable
      shell: bash
      run: |
        ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn"
        echo "c:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn" >> $GITHUB_PATH

    - name: Installing rust targets
      shell: bash
      run: |
        rustup update
        rustup target add x86_64-pc-windows-msvc
        rustup target add i686-pc-windows-msvc
        rustup target add aarch64-pc-windows-msvc

    - name: Unit tests
      working-directory: ./
      shell: bash
      run: |
        cargo test

    - name: Building WIN
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        python GeneratePackage.py -p windows

    - name:  Building DOTNET CORE
      working-directory: ./wrappers/csharp
      shell: bash
      run: |
        python GeneratePackage.py -p dotnet-core

    - uses: actions/upload-artifact@v3
      with:
        name: artifact-staging
        path: |
          wrappers/csharp/windows/**
          wrappers/csharp/dotnet-core/**
