[package]
name = "devolutions-crypto"
version = "0.5.0"
authors = ["Philippe Dugre <pdugre@devolutions.net>", "Mathieu Morrissette <mmorrissette@devolutions.net>"]
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/devolutions/devolutions-crypto"
repository = "https://github.com/devolutions/devolutions-crypto"
description = "An abstraction layer for the cryptography used by Devolutions"

[lib]
name="devolutions_crypto"
crate-type = ["staticlib"]
path = "../src/lib.rs"

[dependencies]
aes = "0.3.2"
block-modes = "0.3.3"
byteorder="1.3.4"
cfg-if = "0.1.10"
hmac = "0.7.1"
pbkdf2 = { version = "0.3.0", default-features = false }
sha2 = "0.8.1"
x25519-dalek = "0.6.0"
subtle = "2.2.2"
zeroize = "1.1.0"
zeroize_derive = "1.0.0"
base64 = "0.12.0"
chacha20poly1305 = "0.4.1"
aead = "0.2.0"
rand = "0.7.3"
sharks = "0.3.2"
rust-argon2 = "0.8.1"
strum = "0.18.0"
strum_macros = "0.18.0"
num_enum = "0.4.3"

[profile.release]
lto = false

[features]
default = []
ffi = []
