/*
 * This source file was generated by the Gradle 'init' task
 */
package org.devolutions.crypto

import kotlin.test.Test

class HashingTest {
    @Test
    fun passwordHashTest() {
        val password = "password".toByteArray(Charsets.UTF_8)
        val hash = hashPassword(password)

        assert(verifyPassword(password, hash))
    }

    @Test
    fun wrongPasswordTest() {
        val password = "password".toByteArray(Charsets.UTF_8)
        val hash = hashPassword(password)

        assert(!verifyPassword("pa\$\$word".toByteArray(), hash))
        assert(!verifyPassword("Password".toByteArray(), hash))
        assert(!verifyPassword("password1".toByteArray(), hash))
    }

    @Test
    fun passwordHashV1Test() {
        val password = "password".toByteArray(Charsets.UTF_8)
        val hash = hashPassword(password, version = PasswordHashVersion.V1)

        assert(verifyPassword(password, hash))
        assert(!verifyPassword("wrongpassword".toByteArray(), hash))
    }

    @Test
    fun passwordHashV2Test() {
        val password = "password".toByteArray(Charsets.UTF_8)
        val hash = hashPassword(password, version = PasswordHashVersion.V2)

        assert(verifyPassword(password, hash))
        assert(!verifyPassword("wrongpassword".toByteArray(), hash))
    }
}