/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertTrue

import org.devolutions.crypto.generateKey

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        generateKey()
    }
}
